### ISSUE TITLE
Hardcoded parameters

### ISSUE THREAD

**Issue by phoebe108** [spatialdev/url2png#1]
It looks like ‘viewport_width’ and ‘delay’ are hardcoded [here](https://github.com/spatialdev/url2png/blob/master/endpoint.js#L58). Would be great to pass in a longer delay time.

**Comment by rgwozdz** [comment]
Thanks…it looks like I started that but never finished.  I’ll keep you posted.

R

On Jan 3, 2017, at 11:42 AM, Phoebe <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like ‘viewport_width’ and ‘delay’ are hardcoded here<https://github.com/spatialdev/url2png/blob/master/endpoint.js#L58>. Would be great to pass in a longer delay time.

**Comment by rgwozdz** [comment]
Fixed in: c8e1e2ca2bd91925ae3be49f01e4614c99a333da
